/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "obldzzvthstaxsntblpq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ibGR6enZ0aHN0YXhzbnRibHBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc5MTI3MTMsImV4cCI6MjA5MzQ4ODcxM30.KRFzMKz-BWidtYRQv-Gi9gVX9-0yaumS7m7vCPB9Hn0"